### ISSUE TITLE
Failed running with docker

### ISSUE THREAD

**Issue by matteospampani** [GaruGaru/conduit#1]
I am trying to run this command from docker with the following command:

`docker run  -e AWS_REGION=eu-west-1 -e AWS_ACCESS_KEY_ID=*** -e AWS_SECRET_ACCESS_KEY=*** garugaru/conduit transfer --source=https://sqs.eu-west-1.amazonaws.com/path/to/source --destination=https://sqs.eu-west-1.amazonaws.com/path/to/destination --delete=true`

And here is the output:

`transfer running, press enter to interrupt.
panic: EOF

goroutine 1 [running]:
github.com/GaruGaru/conduit/cmd.runTransfer(0xdf19e0, 0xc000180b70, 0x0, 0x3)
	/src/cmd/transfer.go:61 +0x393
github.com/spf13/cobra.(*Command).execute(0xdf19e0, 0xc000180ae0, 0x3, 0x3, 0xdf19e0, 0xc000180ae0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xdf1ee0, 0x1, 0x1, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/GaruGaru/conduit/cmd.Execute()
	/src/cmd/root.go:15 +0x32
main.main()
	/src/main.go:8 +0x20
`

**Comment by GaruGaru** [comment]
Hi @matteospampani  thank you very much for the bug report ! 
The issue that you've reported is caused by executing the docker run command without interactive mode, since conduit expects to run in a interactive shell it panics. 

So the solution is to add the `-it` flag to the docker run command.

I've updated the documentation accordingly #2 , and opened a new issue in order to make conduit run also in non interactive mode #3

**Comment by matteospampani** [comment]
Thank you, it works! ;-)
